name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.1.5

      - name: Install Dependencies and Build
        run: |
          npm i
          npm run build
